CREATE TABLE IF NOT EXISTS gk_task.email (
                                                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                                user_id BIGINT REFERENCES gk_task.users(id),
                                                email VARCHAR(200) UNIQUE NOT NULL
                                         );