CREATE TABLE IF NOT EXISTS gk_task.phones (
                                                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                                user_id BIGINT REFERENCES gk_task.users(id),
                                                phone VARCHAR(13) UNIQUE NOT NULL
);